build:
	docker build -t eulershinyproxy -f Dockerfile .

run:
	docker run -d -p 3838:3838  eulershinyproxy      # -d: detach   -p port|publish
                                                         # --rm:  remove container when done
