build:
	docker build -t eulershinyproxy -f Dockerfile .

run:
	docker run --rm  -p 60080:3838  eulershinyproxy      # -d: detach   -p port|publish
                                                             # --rm:  remove container when done
